---
# tasks file for roles/nginx
  - name: install nginx et curl
    apt:
      name: nginx,curl
      state: present
      cache_valid_time: 3600
      update_cache: yes
  - name: remove default conf
    file:
      path: "{{ item }}"
      state: absent
    with_items:
    - "/etc/nginx/sites-available/default"
    - "/etc/nginx/sites-enabled/default"

  - name: install vhost conf
    template:
      src: vhost.conf.j2
      dest: /etc/nginx/sites-available/vhost.conf
      owner: root
      group: root
      mode: 0644
    notify: restart nginx

  - name: create symbolic link
    file:
      src: /etc/nginx/sites-available/vhost.conf
      dest: /etc/nginx/sites-enabled/vhost.conf
      state: link

  - name: flush handslers
    meta: flush_handlers