---
# tasks file for roles/users
- name: create user devops
  user:
    name: devops
    shell: /bin/bash
    groups: sudo
    append: yes
    password: "{{ 'password' | password_hash('sha512') }}"

- name: add devops user to the sudoers
  copy:
    dest: "/etc/sudoers.d/devops"
    content: "devops ALL=(ALL) NOPASSWD: ALL"

- name: deploy ssh key
  authorized_key:
    user: devops
    key: "{{ lookup('file', '/tmp/key_hosts.pub') }}"
    state: present